import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Rick & Morty App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <footer className="w-full border-t border-solid border-t-[#303928] bg-[#141811] px-10 py-8">
          <div className="mx-auto max-w-7xl flex flex-col md:flex-row items-center justify-between gap-6">
            <div className="flex flex-col items-center md:items-start gap-2">
            <span className="text-[#abba9c] text-xs uppercase tracking-widest font-bold">Create By</span>
            <span className="text-white font-bold">Siti Lubna Salsa Bila M</span>
            </div>
            <div className="flex gap-6">
            <a className="text-[#abba9c] hover:text-primary transition-colors" href="#">Next & Tailwind</a>
            </div>
            <div className="text-[#abba9c] text-sm">
              © 2025 Rick & Morty
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
